---
- name: Configure Vault for node2
  copy:
    src: files/vault_node2.hcl
    dest: /etc/vault.d/vault.hcl
    owner: vault
    group: vault

- name: export variables to shell
  shell: |
    export VAULT_ADDR=https://192.168.7.37:8200

- name: Add variable to user .bashrc
  lineinfile:
    path: ~/.bashrc
    line: 'export VAULT_ADDR="https://192.168.7.37:8200"'
    create: yes 